# Generated by Django 5.2 on 2025-05-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kit",
            options={"ordering": ["-date_created"]},
        ),
    ]
